dirs:
  data_dir: ../gen_datasets/20260420_111832_chkpt93
  output_dir: ../gen_datasets_processed/20260420_111832_chkpt93_processed
  processed_dir: ../gen_datasets_processed/20260420_111832_chkpt93_processed/processed_images
  dataset_dir: ../gen_datasets_processed/20260420_111832_chkpt93_processed/processed_dataset

resample:
  new_size: [256, 256, 256]
  interpolator: "bspline" # "nearest" "linear" "bspline" "hamming" "lanczos" "gaussian" "cosine"