dirs:
  data_dir: #../gen_datasets_processed/202.._processed
  output_dir: #../gen_datasets_processed/202..._processed
  processed_dir: #../gen_datasets_processed/202..._processed/processed_images
  dataset_dir: #../gen_datasets_processed/202..._processed/processed_dataset

resample:
  new_size: [256, 256, 256]
  interpolator: "bspline" # "nearest" "linear" "bspline" "hamming" "lanczos" "gaussian" "cosine"